//
// Created by cenka on 1/7/2024.
//

#ifndef JSON_CONVERTER_DEFINES_HPP
#define JSON_CONVERTER_DEFINES_HPP

#define ASCII_JSON_OPENING_CURLY_BRACKET 123
#define ASCII_JSON_CLOSING_CURLY_BRACKET 125

#define ASCII_JSON_OPENING_SQUARE_BRACKETS 91
#define ASCII_JSON_CLOSING_SQUARE_BRACKETS 93

#define ASCII_JSON_DOUBLE_QUOTE 34
#define ASCII_JSON_SINGLE_QUOTE 39
#define ASCII_JSON_COMMA 44

#define ASCII_JSON_OPENING_PARANTHESIS 40
#define ASCII_JSON_CLOSING_PARANTHESIS 41

#define ASCII_JSON_COLON 58

#endif //JSON_CONVERTER_DEFINES_HPP
