//
// Created by cenka on 1/7/2024.
//

#ifndef JSON_CONVERTER_DEFINES_HPP
#define JSON_CONVERTER_DEFINES_HPP

#define JSON_OPENING_CURLY_BRACKET 123
#define JSON_CLOSING_CURLY_BRACKET 125

#define JSON_OPENING_SQUARE_BRACKETS 91
#define JSON_CLOSING_SQUARE_BRACKETS 93

#define JSON_QUOTE 34
#define JSON_COMMA 44

#define JSON_OPENING_PARANTHESIS 40
#define JSON_CLOSING_PARANTHESIS 41

#endif //JSON_CONVERTER_DEFINES_HPP
